### ISSUE TITLE
2 404s for sp.xml

### ISSUE THREAD

**Issue by gdelvalle** [rackerlabs/docs-rackspace-federation#40]
On these pages: 
- https://developer.rackspace.com/docs/rackspace-federation/config-3p-saml/config-okta/okta-setup/
- https://developer.rackspace.com/docs/rackspace-federation/config-3p-saml/config-adfs/adfs-setup/

In the respective sections:
```
2. Fill in the requested SAML information with Rackspace details.

The metadata file contains the latest certificate for signing SAML assertions.

The default values can be retrieved programmatically from the Rackspace service provider metadata file at: https://login.rackspace.com/federate/sp.xml and are shown in the following list:
```

and

```
2. Import the Rackspace metadata by using https://login.rackspace.com/federate/sp.xml or by downloading the https://login.rackspace.com/federate/sp.xml metadata file locally and then uploading it in ADFS.

```

the `https://login.rackspace.com/federate/sp.xm` actually sends me to  `https://developer.rackspace.com/docs/rackspace-federation/config-3p-saml/config-okta/okta-setup/login.rackspace.com/federate/sp.xml`

I think its this line
```
<https:login.rackspace.com/federate/sp.xml>`_ is missing the the // s
```

**Comment by rtgoodwin** [comment]
Good catch, and fixed with your solution exactly! :) Thanks!
